nodeLinker: pnp

packageExtensions:
  "@typescript-eslint/type-utils@*":
    peerDependencies:
      eslint: "*"
      typescript: "*"
  "@typescript-eslint/utils@*":
    peerDependencies:
      eslint: "*"
      typescript: "*"
  typescript-eslint@*:
    peerDependencies:
      eslint: "*"

yarnPath: .yarn/releases/yarn-4.5.3.cjs
