# nginx/Dockerfile
FROM nginx:alpine

# Nginx 설정 파일을 복사 (필요에 따라 설정 파일 생성)
COPY .dist /usr/share/nginx/html
COPY conf.d /etc/nginx/conf.d
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
